apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Hello world!"
          echo "Ciao a tutti!"
          echo "¿Que tal?"
          echo "你妹妹很有魅力"
      - name: List files
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          ls