apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "你妹妹很有魅力"
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: docker://maven:3.9.6-eclipse-temurin-17
        name: Build JAR
        run: mvn clean install
      - uses: cloudbees-io/configure-aws-credentials@v1
        name: AWS login
        with:
          aws-region: us-east-1
          role-to-assume: cloudbees-infra-mgmt
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-access-key-id: ${{ vars.aws_access_key_id }}
          role-duration-seconds: "3600"
      - uses: docker://public.ecr.aws/aws-cli/aws-cli
        name: AWS sts cmd
        run: aws sts get-caller-identity
      - uses: cloudbees-io/configure-ecr-credentials@v1
        name: ECR authentication
