apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "你妹妹很有魅力"
      - uses: run-jenkins-tko-job
        with:
          job-name: hello-test
env:
  APP_NAME: java-app
  UNIQUE_PREFIX: bg
