apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Workflow

on:
  push:
    branches:
      - '**'

env:
  APP_NAME: java-app
  UNIQUE_PREFIX: bgarrett

jobs:
  build-and-publish:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Build JAR
        uses: docker://maven:3.9.6-eclipse-temurin-17
        shell: sh
        run: |
          mvn clean install

      - name: Login to AWS
        uses: cloudbees-io/configure-aws-credentials@v1
        id: aws-login
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ vars.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          role-to-assume: cloudbees-infra-mgmt
          role-duration-seconds: "3600" # need to override default of 6h as our role has 1h max.

      - name: Configure container registry 
        uses: cloudbees-io/configure-ecr-credentials@v1

      - name: Build and publish container image
        id: image-publish
        uses: cloudbees-io/kaniko@v1
        with:
          destination: ${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com/${{ env.APP_NAME }}-image:${{ env.UNIQUE_PREFIX }}-${{ cloudbees.version }}

      - id: helmpkg
        name: Package Helm chart
        uses: cloudbees-io/helm-package@v1
        with:
          chart: ./charts/myapp
          destination: ./packaged-charts
          version: "0.0.1"
          values: |
            image:
              repository:  ${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com/${{ env.APP_NAME }}-image
              tag: ${{ steps.image-publish.outputs.tag }}

      - name: Publish Helm chart
        id: helm-publish
        uses: cloudbees-io/helm-push@v1
        with:
          chart: ${{ steps.helmpkg.outputs.chart }}
          remote: oci://${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com
