apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Workflow

on:
  push:
    branches:
      - '**'

jobs:
  jenkins-test:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Let's call Jenkins from a platform workflow..."
      
      # use the run-jenkins-tko-job preconfigured action to run a job
      - name: Run Jenkins job
        uses: run-jenkins-tko-job
        with:
          job-name: hello-test

