apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Workflow

on:
  push:
    branches:
      - '**'

env:
  APP_NAME: java-app
  UNIQUE_PREFIX: bgarrett

jobs:
  build-and-publish:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
        
      - name: Build JAR
        uses: docker://maven:3.9.6-eclipse-temurin-17
        shell: sh
        run: |
          mvn clean install

      - name: Login to AWS
        uses: tko-prep-configure-aws-credentials
        id: aws-login

      - name: Configure container registry 
        uses: cloudbees-io/configure-ecr-credentials@v1

      - name: Build and publish container image
        id: image-publish
        uses: cloudbees-io/kaniko@v1
        with:
          destination: ${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com/${{ env.APP_NAME }}-image:${{ env.UNIQUE_PREFIX }}-${{ cloudbees.version }}

      - id: helmpkg
        name: Package Helm chart
        uses: cloudbees-io/helm-package@v1
        with:
          chart: ./charts/myapp
          destination: ./packaged-charts
          version: "0.0.1"
          values: |
            image:
              repository:  ${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com/${{ env.APP_NAME }}-image
              tag: ${{ steps.image-publish.outputs.tag }}

      - name: Publish Helm chart
        id: helm-publish
        uses: cloudbees-io/helm-push@v1
        with:
          chart: ${{ steps.helmpkg.outputs.chart }}
          remote: oci://${{ steps.aws-login.outputs.aws-account-id }}.dkr.ecr.us-east-1.amazonaws.com

    outputs:
      chart-location: ${{ steps.helm-publish.outputs.chart }}
      chart-version: ${{ steps.helm-publish.outputs.version }}

  deploy:
    environment: dev
    needs:
      - build-and-publish

    steps:
      - uses: tko-prep-configure-aws-credentials

      - uses: cloudbees-io/configure-eks-credentials@v1
        with:
          name: cloudbees-quickstart-cluster

      - uses: cloudbees-io/configure-ecr-credentials@v1

      - id: install-chart
        name: Install helm chart
        uses: cloudbees-io/helm-install@v1
        with:
          chart-location: ${{ needs.build-and-publish.outputs.chart-location }}
          version: ${{ needs.build-and-publish.outputs.chart-version }}
          release-name: ${{ env.UNIQUE_PREFIX }}-${{ env.APP_NAME }}
          namespace: ${{ env.UNIQUE_PREFIX }}-${{ env.APP_NAME }}
          values: |
            ingress:
              annotations:
                external-dns.alpha.kubernetes.io/hostname: ${{ vars.HOSTNAME }}
              hosts:
                - host: "${{ vars.HOSTNAME }}"
                  paths:
                    - path: /
                      pathType: Prefix
                - paths:
                    - path: /
                      pathType: Prefix